In [7]:
import turicreate

In [8]:
sales = turicreate.SFrame("home_data.sframe")

In [9]:
sales


Columns:
	id	str
	date	datetime
	price	float
	bedrooms	float
	bathrooms	float
	sqft_living	float
	sqft_lot	float
	floors	float
	waterfront	int
	view	int
	condition	int
	grade	float
	sqft_above	float
	sqft_basement	float
	yr_built	float
	yr_renovated	float
	zipcode	str
	lat	float
	long	float
	sqft_living15	float
	sqft_lot15	float

Rows: 21613

Data:
+------------+---------------------------+-----------+----------+-----------+
|     id     |            date           |   price   | bedrooms | bathrooms |
+------------+---------------------------+-----------+----------+-----------+
| 7129300520 | 2014-10-13 00:00:00+00:00 |  221900.0 |   3.0    |    1.0    |
| 6414100192 | 2014-12-09 00:00:00+00:00 |  538000.0 |   3.0    |    2.25   |
| 5631500400 | 2015-02-25 00:00:00+00:00 |  180000.0 |   2.0    |    1.0    |
| 2487200875 | 2014-12-09 00:00:00+00:00 |  604000.0 |   4.0    |    3.0    |
| 1954400510 | 2015-02-18 00:00:00+00:00 |  510000.0 |   3.0    |    2.0    |
| 7237550310 | 2014-05-12 00:00:00+00:00 | 1225000.0 |   4.0    |    4.5    |
| 1321400060 | 2014-06-27 00:00:00+00:00 |  257500.0 |   3.0    |    2.25   |
| 2008000270 | 2015-01-15 00:00:00+00:00 |  291850.0 |   3.0    |    1.5    |
| 2414600126 | 2015-04-15 00:00:00+00:00 |  229500.0 |   3.0    |    1.0    |
| 3793500160 | 2015-03-12 00:00:00+00:00 |  323000.0 |   3.0    |    2.5    |
+------------+---------------------------+-----------+----------+-----------+
+-------------+----------+--------+------------+------+-----------+-------+
| sqft_living | sqft_lot | floors | waterfront | view | condition | grade |
+-------------+----------+--------+------------+------+-----------+-------+
|    1180.0   |  5650.0  |  1.0   |     0      |  0   |     3     |  7.0  |
|    2570.0   |  7242.0  |  2.0   |     0      |  0   |     3     |  7.0  |
|    770.0    | 10000.0  |  1.0   |     0      |  0   |     3     |  6.0  |
|    1960.0   |  5000.0  |  1.0   |     0      |  0   |     5     |  7.0  |
|    1680.0   |  8080.0  |  1.0   |     0      |  0   |     3     |  8.0  |
|    5420.0   | 101930.0 |  1.0   |     0      |  0   |     3     |  11.0 |
|    1715.0   |  6819.0  |  2.0   |     0      |  0   |     3     |  7.0  |
|    1060.0   |  9711.0  |  1.0   |     0      |  0   |     3     |  7.0  |
|    1780.0   |  7470.0  |  1.0   |     0      |  0   |     3     |  7.0  |
|    1890.0   |  6560.0  |  2.0   |     0      |  0   |     3     |  7.0  |
+-------------+----------+--------+------------+------+-----------+-------+
+------------+---------------+----------+--------------+---------+-------------+
| sqft_above | sqft_basement | yr_built | yr_renovated | zipcode |     lat     |
+------------+---------------+----------+--------------+---------+-------------+
|   1180.0   |      0.0      |  1955.0  |     0.0      |  98178  | 47.51123398 |
|   2170.0   |     400.0     |  1951.0  |    1991.0    |  98125  | 47.72102274 |
|   770.0    |      0.0      |  1933.0  |     0.0      |  98028  | 47.73792661 |
|   1050.0   |     910.0     |  1965.0  |     0.0      |  98136  |   47.52082  |
|   1680.0   |      0.0      |  1987.0  |     0.0      |  98074  | 47.61681228 |
|   3890.0   |     1530.0    |  2001.0  |     0.0      |  98053  | 47.65611835 |
|   1715.0   |      0.0      |  1995.0  |     0.0      |  98003  | 47.30972002 |
|   1060.0   |      0.0      |  1963.0  |     0.0      |  98198  | 47.40949984 |
|   1050.0   |     730.0     |  1960.0  |     0.0      |  98146  | 47.51229381 |
|   1890.0   |      0.0      |  2003.0  |     0.0      |  98038  | 47.36840673 |
+------------+---------------+----------+--------------+---------+-------------+
+---------------+---------------+-----+
|      long     | sqft_living15 | ... |
+---------------+---------------+-----+
| -122.25677536 |     1340.0    | ... |
|  -122.3188624 |     1690.0    | ... |
| -122.23319601 |     2720.0    | ... |
| -122.39318505 |     1360.0    | ... |
| -122.04490059 |     1800.0    | ... |
| -122.00528655 |     4760.0    | ... |

In [10]:
import numpy as np

In [17]:
def get_numpy_data(data_sframe, features, output):
    data_sframe['constant'] = 1 # add a constant column to an SFrame
    # prepend variable 'constant' to the features list
    features = ['constant'] + features
    # select the columns of data_SFrame given by the ‘features’ list into the SFrame ‘features_sframe’
    features_sframe = data_sframe[features]

    # this will convert the features_sframe into a numpy matrix:
    features_matrix = features_sframe.to_numpy()
    # assign the column of data_sframe associated with the target to the variable ‘output_sarray’
    output_sarray=data_sframe['price']

    # this will convert the SArray into a numpy array:
    output_array = output_sarray.to_numpy()
    return(features_matrix, output_array)

In [18]:
(example_features, example_output) = get_numpy_data(sales, ['sqft_living'], 'price')

In [20]:
print( example_features[0,:]) # this accesses the first row of the data the ':' indicates 'all columns'
print (example_output[0]) # and the corresponding output

[1.00e+00 1.18e+03]
221900.0


In [21]:
print (example_output)

[221900. 538000. 180000. ... 402101. 400000. 325000.]


In [22]:
print( example_features)

[[1.00e+00 1.18e+03]
 [1.00e+00 2.57e+03]
 [1.00e+00 7.70e+02]
 ...
 [1.00e+00 1.02e+03]
 [1.00e+00 1.60e+03]
 [1.00e+00 1.02e+03]]


In [23]:
def predict_output(feature_matrix, weights):
    # assume feature_matrix is a numpy matrix containing the features as columns and weights is a corresponding numpy array
    # create the predictions vector by using np.dot()
    predictions = np.dot(feature_matrix,weights)

    return(predictions)

In [24]:
my_weights = np.array([1., 1.])

In [26]:
test_predictions = predict_output(example_features, my_weights)
print( test_predictions[0]) # should be 1181.0
print (test_predictions[1]) # should be 2571.0

1181.0
2571.0


In [27]:
def feature_derivative(errors, feature):
    # Assume that errors and feature are both numpy arrays of the same length (number of data points)
    # compute twice the dot product of these vectors as 'derivative' and return the value
    derivative = 2*np.dot(errors,feature)

    return(derivative)

In [28]:
(example_features, example_output) = get_numpy_data(sales, ['sqft_living'], 'price') 
my_weights = np.array([0., 0.]) # this makes all the predictions 0
test_predictions = predict_output(example_features, my_weights) 
# just like SFrames 2 numpy arrays can be elementwise subtracted with '-': 
errors = test_predictions - example_output # prediction errors in this case is just the -example_output
feature = example_features[:,0] # let's compute the derivative with respect to 'constant', the ":" indicates "all rows"
derivative = feature_derivative(errors, feature)
print (derivative)
print (-np.sum(example_output)*2) # should be the same as derivative

-23345850022.0
-23345850022.0


In [29]:
from math import sqrt # recall that the magnitude/length of a vector [g[0], g[1], g[2]] is sqrt(g[0]^2 + g[1]^2 + g[2]^2)

In [42]:
def regression_gradient_descent(feature_matrix, output, initial_weights, step_size, tolerance):
    converged = False 
    weights = np.array(initial_weights) # make sure it's a numpy array
    while not converged:
        # compute the predictions based on feature_matrix and weights using your predict_output() function
        
         predictions = predict_output(feature_matrix, weights)

        # compute the errors as predictions - output
         errors = predictions - output
            gradient_sum_squares = 0 # initialize the gradient sum of squares
            
        # while we haven't reached the tolerance yet, update each feature's weight
           for i in range(len(weights)):
            # loop over each weight
            # Recall that feature_matrix[:, i] is the feature column associated with weights[i]
            # compute the derivative for weight[i]:
            
            derivative = feature_derivative(errors, feature_matrix[:,i])
            print ('derivative for weight at position ' + str(i) + ': ' + str(derivative))
            

            # add the squared value of the derivative to the gradient sum of squares (for assessing convergence)
            gradient_sum_squares = (derivative * derivative) + gradient_sum_squares
                print ('gradient_sum_squares: ' + str(gradient_sum_squares))

            # subtract the step size times the derivative from the current weight
            weights[i] = weights[i] - (step_size * derivative)
            
        # compute the square-root of the gradient sum of squares to get the gradient magnitude:
            gradient_magnitude = sqrt(gradient_sum_squares)
            if counter > 500:
                converged = True
            if gradient_magnitude < tolerance:
                converged = True
            counter = counter + 1
    return(weights)

IndentationError: unexpected indent (<ipython-input-42-0a333b272ce3>, line 14)

In [47]:
def regression_gradient_descent(feature_matrix, output, initial_weights, step_size, tolerance):
    converged = False 
    weights = np.array(initial_weights) # make sure it's a numpy array
    while not converged:
        predictions = predict_output(feature_matrix, weights)
        errors = predictions - output
        gradient_sum_squares = 0
        for i in range(len(weights)):
            derivative = feature_derivative(errors, feature_matrix[:,i])
            print ('derivative for weight at position ' + str(i) + ': ' + str(derivative))
            gradient_sum_squares = (derivative * derivative) + gradient_sum_squares
            print ('gradient_sum_squares: ' + str(gradient_sum_squares))
            weights[i] = weights[i] - (step_size * derivative)
            gradient_magnitude = sqrt(gradient_sum_squares)
            if counter > 500:
                converged = True
            if gradient_magnitude < tolerance:
                converged = True
            
            counter = counter + 1
    
    return(weights)   
        
        
        
        

In [48]:
train_data,test_data = sales.random_split(.8,seed=0)

In [49]:
simple_features = ['sqft_living']
my_output = 'price'
(simple_feature_matrix, output) = get_numpy_data(train_data, simple_features, my_output)
initial_weights = np.array([-47000., 1.])
step_size = 7e-12
tolerance = 2.5e7

In [50]:
regression_gradient_descent(simple_feature_matrix, output, initial_weights, step_size, tolerance)


derivative for weight at position 0: -20314476464.0
gradient_sum_squares: 4.1267795400640994e+20


UnboundLocalError: local variable 'counter' referenced before assignment

In [51]:

def regression_gradient_descent(feature_matrix, output, initial_weights, step_size, tolerance):
    converged = False 
    weights = np.array(initial_weights) # make sure it's a numpy array
#     print weights
    counter = 0
    while not converged:
#         print 'starting iteration: ' + str(counter)
        # compute the predictions based on feature_matrix and weights using your predict_output() function
        predictions = predict_output(feature_matrix, weights)
        # compute the errors as predictions - output
        errors = predictions - output
        gradient_sum_squares = 0 # initialize the gradient sum of squares
        # while we haven't reached the tolerance yet, update each feature's weight
        for i in range(len(weights)): # loop over each weight
            # Recall that feature_matrix[:, i] is the feature column associated with weights[i]
            # compute the derivative for weight[i]:
            derivative = feature_derivative(errors, feature_matrix[:,i])
#             print 'derivative for weight at position ' + str(i) + ': ' + str(derivative)
            # add the squared value of the derivative to the gradient sum of squares (for assessing convergence)
            gradient_sum_squares = (derivative * derivative) + gradient_sum_squares
#             print 'gradient_sum_squares: ' + str(gradient_sum_squares)
            # subtract the step size times the derivative from the current weight
            weights[i] = weights[i] - (step_size * derivative)
        # compute the square-root of the gradient sum of squares to get the gradient matnigude:
        gradient_magnitude = sqrt(gradient_sum_squares)
#         print 'gradient_magnitute: ' + str(gradient_magnitude)
#         print 'tolerance: ' + str(tolerance)
        if counter > 500:
            converged = True
        if gradient_magnitude < tolerance:
            converged = True
        counter = counter + 1
    return(weights)

In [52]:
regression_gradient_descent(simple_feature_matrix, output, initial_weights, step_size, tolerance)

array([-46999.88716555,    281.91211912])

In [53]:
(test_simple_feature_matrix, test_output) = get_numpy_data(test_data, simple_features, my_output)


In [54]:
(test_simple_feature_matrix, test_output) = get_numpy_data(test_data, simple_features, my_output)


In [57]:
my_predictions = predict_output(test_simple_feature_matrix, np.asarray([-46719.20069418,    281.79930582]))
print (my_predictions[0])

356253.80662841996


In [58]:
output = test_data['price']
print (str(type(output)))
print (str(type(my_predictions)))
residuals = my_predictions - output
RSS = (residuals * residuals).sum()
print (RSS)

<class 'turicreate.data_structures.sarray.SArray'>
<class 'numpy.ndarray'>
275393143375677.34


In [59]:
model_features = ['sqft_living', 'sqft_living15'] # sqft_living15 is the average squarefeet for the nearest 15 neighbors. 
my_output = 'price'
(feature_matrix, output) = get_numpy_data(train_data, model_features, my_output)
initial_weights = np.array([-100000., 1., 1.])
step_size = 4e-12
tolerance = 1e9

In [60]:
regression_gradient_descent(feature_matrix, output, initial_weights, step_size, tolerance)

array([-9.99999688e+04,  2.45072603e+02,  6.52795277e+01])

In [61]:
(test_simple_feature_matrix, test_output) = get_numpy_data(test_data, model_features, my_output)

In [62]:
my_predictions2 = predict_output(feature_matrix, np.asarray([ -9.99999688e+04,   2.45072603e+02,   6.52795277e+01]))


In [63]:
my_predictions2[0]


276660.269858

In [64]:
test_data

Columns:
	id	str
	date	datetime
	price	float
	bedrooms	float
	bathrooms	float
	sqft_living	float
	sqft_lot	float
	floors	float
	waterfront	int
	view	int
	condition	int
	grade	float
	sqft_above	float
	sqft_basement	float
	yr_built	float
	yr_renovated	float
	zipcode	str
	lat	float
	long	float
	sqft_living15	float
	sqft_lot15	float
	constant	int

Rows: 4229

Data:
+------------+---------------------------+----------+----------+-----------+
|     id     |            date           |  price   | bedrooms | bathrooms |
+------------+---------------------------+----------+----------+-----------+
| 0114101516 | 2014-05-28 00:00:00+00:00 | 310000.0 |   3.0    |    1.0    |
| 9297300055 | 2015-01-24 00:00:00+00:00 | 650000.0 |   4.0    |    3.0    |
| 1202000200 | 2014-11-03 00:00:00+00:00 | 233000.0 |   3.0    |    2.0    |
| 8562750320 | 2014-11-10 00:00:00+00:00 | 580500.0 |   3.0    |    2.5    |
| 7589200193 | 2014-11-10 00:00:00+00:00 | 535000.0 |   3.0    |    1.0    |
| 2078500320 | 2014-06-20 00:00:00+00:00 | 605000.0 |   4.0    |    2.5    |
| 7766200013 | 2014-08-11 00:00:00+00:00 | 775000.0 |   4.0    |    2.25   |
| 9478500640 | 2014-08-19 00:00:00+00:00 | 292500.0 |   4.0    |    2.5    |
| 9558200045 | 2014-08-28 00:00:00+00:00 | 289000.0 |   3.0    |    1.75   |
| 8820901275 | 2014-06-10 00:00:00+00:00 | 571000.0 |   4.0    |    2.0    |
+------------+---------------------------+----------+----------+-----------+
+-------------+----------+--------+------------+------+-----------+-------+
| sqft_living | sqft_lot | floors | waterfront | view | condition | grade |
+-------------+----------+--------+------------+------+-----------+-------+
|    1430.0   | 19901.0  |  1.5   |     0      |  0   |     4     |  7.0  |
|    2950.0   |  5000.0  |  2.0   |     0      |  3   |     3     |  9.0  |
|    1710.0   |  4697.0  |  1.5   |     0      |  0   |     5     |  6.0  |
|    2320.0   |  3980.0  |  2.0   |     0      |  0   |     3     |  8.0  |
|    1090.0   |  3000.0  |  1.5   |     0      |  0   |     4     |  8.0  |
|    2620.0   |  7553.0  |  2.0   |     0      |  0   |     3     |  8.0  |
|    4220.0   | 24186.0  |  1.0   |     0      |  0   |     3     |  8.0  |
|    2250.0   |  4495.0  |  2.0   |     0      |  0   |     3     |  7.0  |
|    1260.0   |  8400.0  |  1.0   |     0      |  0   |     3     |  7.0  |
|    2750.0   |  7807.0  |  1.5   |     0      |  0   |     5     |  7.0  |
+-------------+----------+--------+------------+------+-----------+-------+
+------------+---------------+----------+--------------+---------+-------------+
| sqft_above | sqft_basement | yr_built | yr_renovated | zipcode |     lat     |
+------------+---------------+----------+--------------+---------+-------------+
|   1430.0   |      0.0      |  1927.0  |     0.0      |  98028  | 47.75584254 |
|   1980.0   |     970.0     |  1979.0  |     0.0      |  98126  | 47.57136955 |
|   1710.0   |      0.0      |  1941.0  |     0.0      |  98002  | 47.30482931 |
|   2320.0   |      0.0      |  2003.0  |     0.0      |  98027  |  47.5391103 |
|   1090.0   |      0.0      |  1929.0  |     0.0      |  98117  | 47.68889559 |
|   2620.0   |      0.0      |  1996.0  |     0.0      |  98056  | 47.53013988 |
|   2600.0   |     1620.0    |  1984.0  |     0.0      |  98166  | 47.44504345 |
|   2250.0   |      0.0      |  2008.0  |     0.0      |  98042  | 47.36628767 |
|   1260.0   |      0.0      |  1954.0  |     0.0      |  98148  | 47.43658598 |
|   2250.0   |     500.0     |  1916.0  |     0.0      |  98125  |  47.7168015 |
+------------+---------------+----------+--------------+---------+-------------+
+---------------+---------------+-----+
|      long     | sqft_living15 | ... |
+---------------+---------------+-----+
| -122.22874498 |     1780.0    | ... |
| -122.37541218 |     2140.0    | ... |
| -122.21774909 |     1030.0    | ... |
| -122.06971484 |     2580.0    | ... |
|  -122.3752359 |     1570.0    | ... |
| -122.18000831 |     2620.0    | ... |
